### ISSUE TITLE
Set custom User-Agent

### ISSUE THREAD

**Issue by scolby33** [scolby33/OCSPdash#12]
In case something goes terribly wrong and we start taking down other people's servers, it'd be nice if they could know who did it.

Easy to set on the `requests` requests, but might require monkeypatching the Censys API thing to change it there.

**Comment by cthoyt** [comment]
I don't think monkey patch - just override the functions in our inherited version of the class... maybe re-write bits?

If you want to add hooks in then it might even be a good idea to refactor the class and make a PR to them

**Comment by scolby33** [comment]
The Censys api creates a `requests.Session()` [here](https://github.com/Censys/censys-python/blob/cc4993aa2a7542f220a13169b324e3cb20daf056/censys/base.py#L59). It should be easy to update the headers with the new User-Agent just like they do on [line 62](https://github.com/Censys/censys-python/blob/cc4993aa2a7542f220a13169b324e3cb20daf056/censys/base.py#L62).

Perhaps we should also use a `Session` in `server_query` and the `cli` to manage the headers.

P.S. I tried just putting the link in, but I guess code snippets only work on your own repo.

**Comment by scolby33** [comment]
I'll change this for our usages of `requests` explicitly but I'll wait on modifying the Censys api stuff until I hear back from the pull request or too much time passes.

**Comment by scolby33** [comment]
Well that was fast! It got merged. Now do we just specify the GitHub commit in setup.py and requirements until they make a release? I think so.

**Comment by scolby33** [comment]
Never mind, that doesn't work. We'll have to wait for a release from Censys' end.

See a5903154ccd6be5404e5929056b893dcb272a4a3

**Comment by cthoyt** [comment]
You can specify the git location in requirements not setup.py

**Comment by scolby33** [comment]
You can set it in setup.py with some strange contortions.

However, the real problem is if I specify version 0.0.7, then it gets it directly from PyPI. If I make up a version like 0.0.7-dev, then it'll get it from GitHub but then pkg_resources can't verify it's there when running the CLI--it sees a version mismatch.

*shrug* I'm willing to wait.

**Comment by cthoyt** [comment]
Hmm okay i saw what you did. It's wayyy complicated so hopefully they'll make a new release soon
