### ISSUE TITLE
Automatically get location

### ISSUE THREAD

**Issue by cthoyt** [scolby33/OCSPdash#13]
Is there a clever way to do this? Maybe use the external IP address as the location?

**Comment by scolby33** [comment]
I like the idea of locations being like users. The biggest reason I changed the name from User is so members of the User table can be admins and that is divorced entirely from those with the ability to submit results.

**Comment by cthoyt** [comment]
Aha. That's what the Role table is for in flask security, which we'll get to!

**Comment by cthoyt** [comment]
Hmm i wonder if you could use the public key thing and play nice with flask security so you wouldn't need a password... or just have one anyway in addition to the public key? I don't know how your user creation procedure works

**Comment by scolby33** [comment]
We've moved on from this architecture, so this can be closed.
