### ISSUE TITLE
Switch to default ordered dict

### ISSUE THREAD

**Issue by cthoyt** [scolby33/OCSPdash#16]
https://github.com/scolby33/OCSPdash/blob/9938b2142e297252d601b971708413dd1ccba022/src/ocspdash/manager.py#L222

This is emulating default dict behavior, so lets just make a default ordered dict class with this recipe https://stackoverflow.com/questions/6190331/can-i-do-an-ordered-default-dict-in-python

**Comment by scolby33** [comment]
Throw it in `util.py` and go ahead!
