### ISSUE TITLE
Allow users with ocspscrape to change their location name

### ISSUE THREAD

**Issue by cthoyt** [scolby33/OCSPdash#23]

**Comment by scolby33** [comment]
Why?

**Comment by cthoyt** [comment]
Because I want there to be a reasonable way to fix your labels of "Scott" and "Scott 2" 😛

**Comment by scolby33** [comment]
Executive decision: it's a feature :P

**Comment by cthoyt** [comment]
What?

**Comment by scolby33** [comment]
I definitely don't want to allow this via the REST api. I'd be open to adding something in the ocspdash CLI to do it directly in the database, but I'd almost rather it just be done with `psql` or whatever.

**Comment by cthoyt** [comment]
Fine :/
