### ISSUE TITLE
Manager.get_top_authorities doesn't always return n authorities

### ISSUE THREAD

**Issue by scolby33** [scolby33/OCSPdash#3]
If there are fewer `Authority`s in the db than are requested by a call to `Manager.get_top_authorities` then fewer are returned than were requested. Should new ones be found to always return exactly n `Authority`s, should an error be raised if this happens, or should it just be ignored?

@cthoyt thoughts?

**Comment by cthoyt** [comment]
I would say if there are fewer than n authorities, just return what you can

**Comment by scolby33** [comment]
That certainly seems the easiest approach. I'll just document it that way.
