### ISSUE TITLE
Update to python37 only

### ISSUE THREAD

**Issue by cthoyt** [scolby33/OCSPdash#36]
Switch to only Python 3.7 and update all references to 3.6 (Pipfile, docs, readme, etc.)

What 37 only features can we stick in the setup so nothing can happen? Like using f-strings for 36 :)

**Comment by scolby33** [comment]
```python
from __future__ import annotations

class Whatever:
    @classmethod
    def make_whatever(cls) -> Whatever:
        pass
```
That'll do it.
https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations

P.S. I hate that they named that future just plain "annotations"

**Comment by cthoyt** [comment]
there you go

**Comment by scolby33** [comment]
Need to update docs and badges in the readme and the docs.
