### ISSUE TITLE
JSON Serialization of the payload

### ISSUE THREAD

**Issue by scolby33** [scolby33/OCSPdash#7]
See [here](https://github.com/scolby33/OCSPdash/blob/c9801d21b1bb97698f4acd67869f74c17571138f/src/ocspdash/web/app.py#L65). How do you do this recursively on objects?

**Comment by cthoyt** [comment]
Monkey fucking patch the json module

```
from json import JSONEncoder


def _default(self, obj):
    return getattr(obj.__class__, "to_json", _default.default)(obj)


_default.default = JSONEncoder().default  # Save unmodified default.
JSONEncoder.default = _default  # replacement
```

**Comment by scolby33** [comment]
Why doesn't it have like `__to_json__` that people can just implement on all their objects? That would have been the smart thing to do.

**Comment by cthoyt** [comment]
Yeah so jupyter looks for these magic dunder methods... It's also possible that we could make a custom decoder class and tell `jsonify` to use it... but i think monkey patching is probably fine

**Comment by scolby33** [comment]
I did it in `__init__.py` because I'm bad like that.
