### ISSUE TITLE
get_all_locations_with_test_results

### ISSUE THREAD

**Issue by scolby33** [scolby33/OCSPdash#8]
I don't know how to make the SQL query such that it only returns `User` objects if they have at least one associates `Result` object.

https://github.com/scolby33/OCSPdash/blob/c9801d21b1bb97698f4acd67869f74c17571138f/src/ocspdash/web/manager.py#L206

**Comment by cthoyt** [comment]
you know there's this new code snippet thing you can do to put live code into the issues?

https://github.com/scolby33/OCSPdash/blob/c9801d21b1bb97698f4acd67869f74c17571138f/src/ocspdash/web/manager.py#L206

**Comment by scolby33** [comment]
Did not know that. Looks like you just put the bare link in? Cray.
